# Generated by Django 6.0 on 2025-12-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairysyncapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='farmname',
            new_name='farm',
        ),
    ]
