# Generated by Django 6.0 on 2025-12-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairysyncapp', '0002_rename_farmname_farmer_farm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalId', models.CharField(max_length=150)),
                ('animalName', models.CharField(max_length=100)),
                ('tagNumber', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('species', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
    ]
