# Generated by Django 6.0 on 2025-12-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairysyncapp', '0003_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalId', models.CharField(max_length=200)),
                ('animalName', models.CharField(max_length=200)),
                ('animalDob', models.DateField()),
                ('animalAge', models.IntegerField()),
                ('animalSpecies', models.CharField(max_length=300)),
                ('animalBreed', models.CharField(max_length=300)),
                ('animalGemder', models.CharField(max_length=230)),
                ('animalWeight', models.FloatField(max_length=200)),
                ('animalHealthStatus', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
