# Generated by Django 6.0 on 2025-12-07 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairysyncapp', '0004_animaldata_delete_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(max_length=50, unique=True, verbose_name='Animal ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Animal Name')),
                ('ear_tag', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ear Tag Number')),
                ('species', models.CharField(choices=[('Cow', 'Cow'), ('Goat', 'Goat'), ('Sheep', 'Sheep')], max_length=20, verbose_name='Species')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='Breed')),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=10, verbose_name='Gender')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('age_years', models.IntegerField(default=0, verbose_name='Age (Years)')),
                ('age_months', models.IntegerField(default=0, verbose_name='Age (Months)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animal-photos/', verbose_name='Animal Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Height (cm)')),
                ('body_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Body Length (cm)')),
                ('chest_girth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Chest Girth (cm)')),
                ('body_condition_score', models.CharField(choices=[('1', '1 -Very Thin'), ('2', '2 - Thin'), ('3', '3 - Ideal'), ('4', '4 - Overweight'), ('5', '5 - Obese')], default='3', max_length=1, verbose_name='Body Condition Score (1-5)')),
                ('identification_marks', models.TextField(blank=True, null=True, verbose_name='Identification Marks')),
                ('physical_notes', models.TextField(blank=True, null=True, verbose_name='Physical Notes')),
                ('acquisition_date', models.DateField(verbose_name='Acquisition Date')),
                ('source', models.CharField(choices=[('born_on_farm', 'Born on Farm'), ('purchased', 'Purchased'), ('gift', 'Gift/Donation'), ('other', 'Other')], max_length=20, verbose_name='Source')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Purchase Price')),
                ('seller', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seller Information')),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('deceased', 'Deceased'), ('inactive', 'Inactive'), ('transferred', 'Transferred')], default='active', max_length=20, verbose_name='Current Status')),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('observation', 'Under Observation'), ('sick', 'Sick'), ('recovering', 'Recovering')], default='healthy', max_length=20, verbose_name='Health Status')),
                ('health_notes', models.TextField(blank=True, null=True, verbose_name='Health Notes')),
                ('group', models.CharField(blank=True, max_length=100, null=True, verbose_name='Group/ Pen Assignment')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location/Pen Number')),
                ('initial_notes', models.TextField(blank=True, null=True, verbose_name='Initial Notes')),
            ],
        ),
        migrations.CreateModel(
            name='MilkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_yield', models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Morning Yield (Liters)')),
                ('evening_yield', models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Evening Yield (Liters)')),
                ('total_yield', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Total Daily Yield (Liters)')),
                ('quality', models.CharField(choices=[('good', 'Good'), ('excellent', 'Excellent'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=10, verbose_name='Milk Quality')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_logs', to='dairysyncapp.animal')),
            ],
        ),
        migrations.DeleteModel(
            name='AnimalData',
        ),
    ]
