# Generated by Django 6.0 on 2025-12-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairysyncapp', '0006_remove_animal_acquisition_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='health_status',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
