# Generated by Django 6.0 on 2025-12-11 08:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairysyncapp', '0010_profile_delete_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='animal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('recovering', 'Recovering'), ('unknown', 'Unknown')], default='healthy', max_length=20),
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_milk', models.DecimalField(decimal_places=3, help_text='Litres', max_digits=6)),
                ('afternoon_milk', models.DecimalField(decimal_places=3, help_text='Litres', max_digits=6)),
                ('evening_milk', models.DecimalField(decimal_places=3, help_text='Litres', max_digits=6)),
                ('feed_amount', models.DecimalField(decimal_places=3, default=0, help_text='Kilograms', max_digits=6)),
                ('water', models.DecimalField(decimal_places=3, default=0, help_text='Litres', max_digits=6)),
                ('temperature', models.DecimalField(blank=True, decimal_places=3, help_text='°C', max_digits=6, null=True)),
                ('health_observations', models.CharField(choices=[('normal', 'Normal'), ('slight_concern', 'Slight Concern'), ('needs_attention', 'Needs Attention'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('activity', models.CharField(choices=[('grazing', 'Grazing'), ('resting', 'Resting'), ('medical_treatment', 'Medical_treatment'), ('exercise', 'Exercise'), ('breeding', 'Breeding'), ('other', 'Other')], default='grazing', max_length=50)),
                ('notes', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='dairysyncapp.animal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('animal', 'date')},
            },
        ),
    ]
