# Generated by Django 6.0 on 2025-12-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairysyncapp', '0011_alter_animal_options_animal_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='water',
            field=models.DecimalField(decimal_places=3, help_text='Litres', max_digits=6),
        ),
    ]
