# Generated by Django 6.0 on 2025-12-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairysyncapp', '0012_alter_dailylog_water'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='activity',
            field=models.CharField(choices=[('grazing', 'Grazing'), ('resting', 'Resting'), ('medical_treatment', 'Medical_treatment'), ('exercise', 'Exercise'), ('breeding', 'Breeding'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='health_observations',
            field=models.CharField(choices=[('normal', 'Normal'), ('slight_concern', 'Slight Concern'), ('needs_attention', 'Needs Attention'), ('critical', 'Critical')], max_length=20),
        ),
    ]
