# Generated by Django 6.0 on 2025-12-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairysyncapp', '0013_alter_dailylog_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='feed_amount',
            field=models.DecimalField(decimal_places=3, help_text='Kilograms', max_digits=6),
        ),
    ]
